name: Auto Approval
on: pull_request_target
jobs:
  auto-approve-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Approve Dependabot updates
        uses: hmarr/auto-approve-action@v3.1.0
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
